### ISSUE TITLE
More improvements to transcribing UI

### ISSUE THREAD

**Issue by leihelondon** [bbc/digital-paper-edit-storybook#105]
**Acceptance criteria**
- [x] Remove messages "stripping...", "converting...". Immediately show "Transcribing..." after uploading has finished. 
- [x] ~~Fix bug: when multiple files are uploaded, the progress bars jump and don't render properly~~ [see [Firebase#270](https://github.com/bbc/digital-paper-edit-firebase/issues/270)]
- [x] ~~Fix bug: After uploading a new file, the card jumps from the top of the transcript column. Implement a sort to handle this~~ [see [Firebase#269](https://github.com/bbc/digital-paper-edit-firebase/issues/269)]
- [x] Implement [UX designs](https://app.zeplin.io/project/5ce554083480691e05af2f74/screen/60ab707c3783aa5e0d9c84df) for closing tab when media file is uploading

**Comment by allishultes** [comment]
Started on Storybook branch [105-transcript-improvements](https://github.com/bbc/digital-paper-edit-storybook/tree/105-transcript-improvements)
