### ISSUE TITLE
Component: TranscriptCard File upload progress bar

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-storybook#35]
**Is your feature request related to a problem? Please describe.**
During uploading, we want to use a progress bar to show:
1. progress
2. that users should not move away from the page

**Describe the solution you'd like**
Users are freely able to move away from the page, and they won't know that their uploads would've failed. Let them know that it will be a lossy process and also let them know the state of the upload.

**Describe alternatives you've considered**

**Additional context**

**Comment by bennuttall** [comment]
This wants something like:

```js
window.addEventListener("beforeunload", (ev) => {...})
```

Then inside the function, look at the upload state and conditionally show a prompt.

**Comment by katiaartsenkova** [comment]
I've got some changes on branch i35 - at the moment it is alerting the user and preventing from leaving/reloading the page in case if new transcript is still uploading

**Comment by emettely** [comment]
Is there a PR?
