### ISSUE TITLE
after re-sizing the progress-bar, it loses accuracy 

### ISSUE THREAD

**Issue by pietrop** [bbc/digital-paper-edit-storybook#40]
## expected behavior 
![progress-bar-ok](https://user-images.githubusercontent.com/4661975/73215196-8d62a580-4121-11ea-9ea6-162dbf5af129.gif)

## Behavior after resizing screen 
![progress-bar-ok-issue](https://user-images.githubusercontent.com/4661975/73215250-a8351a00-4121-11ea-966b-c542d74b4f62.gif)

not urgent, but flagging it in case anyone else come across it, first noticed in electron app.

**Comment by emettely** [comment]
Apologies I thought this was merged as part of #42.

**Comment by emettely** [comment]
Solved it :) @pietrop https://github.com/bbc/digital-paper-edit-storybook/pull/47
