### ISSUE TITLE
Remove postinstall script for published package

### ISSUE THREAD

**Issue by tamsingreen** [bbc/digital-paper-edit-storybook#91]
When storybook v.1.23.0 is installed as a dependency (ie in Firebase), it fails at the postinstall script as there is no .git folder. (eg run `npm i @bbc/digital-paper-edit-storybook@1.23.0`)

Proposed solution:
Adapt tools/createDist.js to remove the "postinstall" script in the same way it already does with the array of react dependencies.

**Comment by allishultes** [comment]
The released changes haven't fixed this issue. I modified the postinstall script to run `husky install` which fails with the error below:

<img width="645" alt="Screenshot 2021-05-12 at 09 10 37" src="https://user-images.githubusercontent.com/22618458/117941525-16dfbc00-b302-11eb-8ea4-38ca4abd86f5.png">

I'll revert to removing the script.
